apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: asr-api-ingress
  namespace: forensic-tools
  annotations:
    traefik.ingress.io/router.entrypoints: web
spec:
  rules:
    - host: asr.api.k25.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: asr-api
                port:
                  number: 80

