apiVersion: v1
kind: Service
metadata:
  name: asr-api
  namespace: forensic-tools
spec:
  selector:
    app: asr-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: ClusterIP

